### ISSUE TITLE
Help users create/select a subscriber endpoint

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azureeventgrid#18]
Most of the 'getting started' docs recommend using hookbin to start off, but I've never gotten that to work:
https://docs.microsoft.com/azure/storage/blobs/storage-blob-event-quickstart?toc=%2fazure%2fevent-grid%2ftoc.json

I have better luck just using an Azure Function, but that's more complicated (especially if users aren't familiar with functions). Here's the docs on that: https://docs.microsoft.com/azure/azure-functions/functions-bindings-event-grid

**Comment by jinglouMSFT** [comment]
The extension is being deprecated.
