### ISSUE TITLE
Allow using a storage queue instead of Webhook for subscriber endpoint

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azureeventgrid#19]
When creating an Event Grid Subscription, we only let people specify a webhook for the subscriber endpoint. However, it might be easier for people to use a storage queue:
https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-queue-storage

**Comment by jinglouMSFT** [comment]
The extension is being deprecated. No new work will be done.
