### ISSUE TITLE
Ensure event JSON is valid before sending

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureeventgrid#24]
The error detection for events are a bit vague today.  We could probably do some JSON parsing to make sure that the necessary properties exist before an event is sent out.

Repro steps:
1. Generate a Mock Event
1. Change eventSchema to an incorrect property (ie eventsdfasdfsSchema)
1. Try to send to preview

Action: azureEventGridSubscription.sendEvents
Error type: TypeError
Error Message: Cannot convert undefined or null to object

Version: 0.1.0
OS: win32

**Comment by jinglouMSFT** [comment]
The extension is being deprecated. No new work will be done on it.
