### ISSUE TITLE
Sign-In Support For Multiple Tenents

### ISSUE THREAD

**Issue by MateusAmin** [Microsoft/vscode-azureeventgrid#37]
My account has access to multiple tenants. I would need to specify which one so that it can find the subscriptions.

Currently it finds no subscription from any of my tenants.

**Comment by MateusAmin** [comment]
After browsing your source code I saw that you use the Azure Account extension. This does look like it has the options I need.

**Comment by MateusAmin** [comment]
I am going to look into adding my use case to the documentation.

**Comment by MateusAmin** [comment]
https://github.com/Microsoft/vscode-azure-account/pull/107

**Comment by MateusAmin** [comment]
https://github.com/Microsoft/vscode-azureeventgrid/pull/38

**Comment by MateusAmin** [comment]
Feel free to take my suggested edits with a large grain of salt. :)

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azureeventgrid/pull/38
