### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Omaralkhanjy94** [microsoft/vscode-azureeventgrid#65]
- Issue Type: `Performance`
- Extension Name: `vscode-azureeventgrid`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\user\ms-azuretools.vscode-azureeventgrid-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jinglouMSFT** [comment]
This extension is being deprecated due to low usage. No additional work will be done on it.
